# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_set_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_22 = QtWidgets.QWidget(self.widget)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_21.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.widget_22)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        self.lineEdit_BposX = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_BposX.setObjectName("lineEdit_BposX")
        self.horizontalLayout_21.addWidget(self.lineEdit_BposX)
        self.label_14 = QtWidgets.QLabel(self.widget_22)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_21.addWidget(self.label_14)
        self.lineEdit_BposY = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_BposY.setObjectName("lineEdit_BposY")
        self.horizontalLayout_21.addWidget(self.lineEdit_BposY)
        self.label_15 = QtWidgets.QLabel(self.widget_22)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.lineEdit_BposZ = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit_BposZ.setObjectName("lineEdit_BposZ")
        self.horizontalLayout_21.addWidget(self.lineEdit_BposZ)
        self.verticalLayout_2.addWidget(self.widget_22)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置杆臂值"))
        self.label_13.setText(_translate("Dialog", "X"))
        self.lineEdit_BposX.setText(_translate("Dialog", "0"))
        self.lineEdit_BposX.setPlaceholderText(_translate("Dialog", "0"))
        self.label_14.setText(_translate("Dialog", "Y"))
        self.lineEdit_BposY.setText(_translate("Dialog", "0"))
        self.lineEdit_BposY.setPlaceholderText(_translate("Dialog", "0"))
        self.label_15.setText(_translate("Dialog", "Z"))
        self.lineEdit_BposZ.setText(_translate("Dialog", "0"))
        self.lineEdit_BposZ.setPlaceholderText(_translate("Dialog", "0"))
